[tool.mypy]
python_version = "3.11"
warn_return_any = true
warn_unused_configs = true
files = [
    "pysecurity",
    "manage.py",
]
exclude = []

[tool.pytest.ini_options]
pythonpath = "pysecurity/do_not_browse"
DJANGO_SETTINGS_MODULE = "pysecurity.settings"
# -- recommended but optional:
python_files = ["tests.py", "test_*.py", "*_tests.py"]
django_find_project = false

